


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."media_metadata_input" AS (
	"id" "uuid",
	"path" "text",
	"alt" "text",
	"type" "text",
	"tag_slugs" "text"[]
);


ALTER TYPE "public"."media_metadata_input" OWNER TO "postgres";


CREATE TYPE "public"."new_image_with_tags" AS (
	"id" "uuid",
	"path" "text",
	"alt" "text",
	"tag_slugs" "text"[]
);


ALTER TYPE "public"."new_image_with_tags" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."media_metadata_autofill_sort_key"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin
  if new.sort_key is null then
    select coalesce(max(i.sort_key), 0) + 10
      into new.sort_key
    from public.media_metadata i;
  end if;

  return new;
end;
$$;


ALTER FUNCTION "public"."media_metadata_autofill_sort_key"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."on_storage_objects_write"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
begin



  return new;
end;
$$;


ALTER FUNCTION "public"."on_storage_objects_write"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."address" (
    "id" bigint NOT NULL,
    "street" "text",
    "city" "text",
    "state" "text",
    "zip" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."address" OWNER TO "postgres";


ALTER TABLE "public"."address" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."address_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" bigint NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "title" "text",
    "venue" "text",
    "description" "text",
    "address_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."events" OWNER TO "postgres";


ALTER TABLE "public"."events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."file_extensions" (
    "id" bigint NOT NULL,
    "extension" "text" NOT NULL,
    "mime_type" "text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    CONSTRAINT "file_extensions_extension_check" CHECK (("extension" = "lower"("extension"))),
    CONSTRAINT "file_extensions_extension_check1" CHECK (("extension" ~ '^[a-z0-9]+$'::"text"))
);


ALTER TABLE "public"."file_extensions" OWNER TO "supabase_admin";


CREATE SEQUENCE IF NOT EXISTS "public"."file_extensions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."file_extensions_id_seq" OWNER TO "supabase_admin";


ALTER SEQUENCE "public"."file_extensions_id_seq" OWNED BY "public"."file_extensions"."id";



CREATE OR REPLACE VIEW "public"."images" AS
 WITH "matched" AS (
         SELECT ("regexp_match"("o"."name", '^(.*)-\d+\.\w+$'::"text"))[1] AS "filename_base",
            ("o"."metadata" ->> 'mimetype'::"text") AS "mimetype",
            "concat"('/', "o"."bucket_id", '/', "o"."name") AS "src",
            (("o"."user_metadata" ->> 'width'::"text"))::integer AS "width",
            (("o"."user_metadata" ->> 'height'::"text"))::integer AS "height",
            ("o"."user_metadata" ->> 'alt'::"text") AS "alt",
            COALESCE(("o"."user_metadata" -> 'tags'::"text"), '[]'::"jsonb") AS "tags"
           FROM "storage"."objects" "o"
          WHERE (("o"."name" ~ '^.+-\d+\.\w+$'::"text") AND (("o"."metadata" ->> 'mimetype'::"text") ~~ 'image%'::"text"))
        ), "grouped_files" AS (
         SELECT "matched"."filename_base",
            "matched"."mimetype",
            "matched"."alt",
            "matched"."tags",
            "jsonb_agg"("jsonb_build_object"('src', "matched"."src", 'width', "matched"."width", 'height', "matched"."height") ORDER BY "matched"."width", "matched"."height", "matched"."src") AS "srcList"
           FROM "matched"
          GROUP BY "matched"."filename_base", "matched"."mimetype", "matched"."alt", "matched"."tags"
        )
 SELECT "filename_base",
    "jsonb_agg"("jsonb_build_object"('mimetype', "mimetype", 'srcList', "srcList", 'alt', "alt", 'tags', "tags") ORDER BY "mimetype") AS "files"
   FROM "grouped_files"
  GROUP BY "filename_base";


ALTER VIEW "public"."images" OWNER TO "supabase_admin";


CREATE MATERIALIZED VIEW "public"."images_mv" AS
 WITH "matched" AS (
         SELECT ("regexp_match"("o"."name", '^(.*)-\d+\.\w+$'::"text"))[1] AS "filename_base",
            ("o"."metadata" ->> 'mimetype'::"text") AS "mimetype",
            "concat"('/', "o"."bucket_id", '/', "o"."name") AS "src",
            (("o"."user_metadata" ->> 'width'::"text"))::integer AS "width",
            (("o"."user_metadata" ->> 'height'::"text"))::integer AS "height",
            ("o"."user_metadata" ->> 'alt'::"text") AS "alt",
            COALESCE(("o"."user_metadata" -> 'tags'::"text"), '[]'::"jsonb") AS "tags_json"
           FROM "storage"."objects" "o"
          WHERE (("o"."name" ~ '^.+-\d+\.\w+$'::"text") AND (("o"."metadata" ->> 'mimetype'::"text") ~~ 'image%'::"text"))
        ), "grouped_files" AS (
         SELECT "matched"."filename_base",
            "matched"."mimetype",
            "jsonb_agg"("jsonb_build_object"('src', "matched"."src", 'width', "matched"."width", 'height', "matched"."height") ORDER BY "matched"."width", "matched"."height", "matched"."src") AS "srcList"
           FROM "matched"
          GROUP BY "matched"."filename_base", "matched"."mimetype"
        ), "files_agg" AS (
         SELECT "grouped_files"."filename_base",
            "jsonb_agg"("jsonb_build_object"('mimetype', "grouped_files"."mimetype", 'srcList', "grouped_files"."srcList") ORDER BY "grouped_files"."mimetype") AS "files"
           FROM "grouped_files"
          GROUP BY "grouped_files"."filename_base"
        ), "image_meta" AS (
         SELECT "m"."filename_base",
            "min"("m"."alt") FILTER (WHERE ("m"."alt" IS NOT NULL)) AS "alt",
            COALESCE("array_agg"(DISTINCT "t"."tag" ORDER BY "t"."tag") FILTER (WHERE ("t"."tag" IS NOT NULL)), '{}'::"text"[]) AS "tags"
           FROM ("matched" "m"
             LEFT JOIN LATERAL "jsonb_array_elements_text"("m"."tags_json") "t"("tag") ON (true))
          GROUP BY "m"."filename_base"
        )
 SELECT "f"."filename_base",
    "f"."files",
    "im"."alt",
    "im"."tags"
   FROM ("files_agg" "f"
     JOIN "image_meta" "im" USING ("filename_base"))
  WITH NO DATA;


ALTER MATERIALIZED VIEW "public"."images_mv" OWNER TO "supabase_admin";


CREATE OR REPLACE VIEW "public"."media_bucket_metadata" WITH ("security_invoker"='on') AS
 SELECT "name" AS "path",
    ("metadata" ->> 'mimetype'::"text") AS "mimeType",
    ("user_metadata" ->> 'alt'::"text") AS "alt",
    ARRAY( SELECT "jsonb_array_elements_text"((("objects"."user_metadata" ->> 'tags'::"text"))::"jsonb") AS "jsonb_array_elements_text") AS "tags"
   FROM "storage"."objects"
  WHERE (("name" !~ '(^|/)\.[^/]+$'::"text") AND ("bucket_id" = 'public_media'::"text"));


ALTER VIEW "public"."media_bucket_metadata" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."media_files" AS
 WITH "matched_files" AS (
         SELECT ("regexp_match"("o"."name", ( SELECT (('^(.+?)\.('::"text" || "string_agg"("file_extensions"."extension", '|'::"text")) || ')$'::"text")
                   FROM "public"."file_extensions"
                  WHERE "file_extensions"."is_active")))[1] AS "filenameBase",
            ("o"."metadata" ->> 'mimetype'::"text") AS "mimeType",
            "o"."name" AS "filename",
            COALESCE((("o"."user_metadata" ->> 'default'::"text"))::boolean, false) AS "is_default",
            ("o"."user_metadata" ->> 'alt'::"text") AS "alt"
           FROM "storage"."objects" "o"
        ), "grouped" AS (
         SELECT "matched_files"."filenameBase",
            "matched_files"."mimeType",
            "array_agg"("matched_files"."filename" ORDER BY "matched_files"."filename") AS "srcset",
            ("array_agg"("matched_files"."filename" ORDER BY "matched_files"."filename") FILTER (WHERE "matched_files"."is_default"))[1] AS "default_filename",
            "matched_files"."alt"
           FROM "matched_files"
          WHERE ("matched_files"."filenameBase" IS NOT NULL)
          GROUP BY "matched_files"."filenameBase", "matched_files"."mimeType", "matched_files"."alt"
        )
 SELECT "filenameBase",
    "srcset",
    COALESCE("default_filename", "srcset"[2], "srcset"[1]) AS "defaultFilename",
    "mimeType",
    COALESCE("alt", "filenameBase") AS "alt"
   FROM "grouped";


ALTER VIEW "public"."media_files" OWNER TO "supabase_admin";


CREATE TABLE IF NOT EXISTS "public"."songs" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."songs" OWNER TO "postgres";


ALTER TABLE "public"."songs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."songs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."file_extensions" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."file_extensions_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."address"
    ADD CONSTRAINT "address_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."file_extensions"
    ADD CONSTRAINT "file_extensions_extension_key" UNIQUE ("extension");



ALTER TABLE ONLY "public"."file_extensions"
    ADD CONSTRAINT "file_extensions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "images_mv_filename_base_idx" ON "public"."images_mv" USING "btree" ("filename_base");



CREATE INDEX "images_mv_tags_gin" ON "public"."images_mv" USING "gin" ("tags");



ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."address"("id") ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."address" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."events" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."songs" FOR SELECT USING (true);



ALTER TABLE "public"."address" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."songs" ENABLE ROW LEVEL SECURITY;


REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."media_metadata_autofill_sort_key"() TO "anon";
GRANT ALL ON FUNCTION "public"."media_metadata_autofill_sort_key"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."media_metadata_autofill_sort_key"() TO "service_role";



GRANT ALL ON FUNCTION "public"."on_storage_objects_write"() TO "anon";
GRANT ALL ON FUNCTION "public"."on_storage_objects_write"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."on_storage_objects_write"() TO "service_role";



GRANT ALL ON TABLE "public"."address" TO "anon";
GRANT ALL ON TABLE "public"."address" TO "authenticated";
GRANT ALL ON TABLE "public"."address" TO "service_role";



GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."address_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."media_bucket_metadata" TO "anon";
GRANT ALL ON TABLE "public"."media_bucket_metadata" TO "authenticated";
GRANT ALL ON TABLE "public"."media_bucket_metadata" TO "service_role";



GRANT ALL ON TABLE "public"."songs" TO "anon";
GRANT ALL ON TABLE "public"."songs" TO "authenticated";
GRANT ALL ON TABLE "public"."songs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";




