import type { Event } from "./types";

export const DUMMY_EVENTS: Event[] = [
  {
    date: new Date(2023, 11, 1),
    title: "A Hard Day's Night",
    venue: "The Royal Albert Hall",
    address: {
      street: "123 London Bridge",
      city: "London",
      state: "United Kingdom",
      zip: "SW1A 1AA",
    },
    description: "A classic concert experience",
  },
  {
    date: new Date(2023, 11, 2),
    title: "Buddy Holly and the Winter Dance Party (Buddy Holly, Ritchie Valens, Big Bopper, Dion and the Belmonts, Bobby Vee)",
    venue: "The Royal Albert Hall",
    address: {
      street: "123 London Bridge",
      city: "London",
      state: "United Kingdom",
      zip: "SW1A 1AA",
    },
    description: "A classic concert experience",
  },
  {
    date: new Date(2023, 11, 3),
    title: "The Beatles",
    venue: "The Royal Albert Hall",
    address: {
      street: "123 London Bridge",
      city: "London",
      state: "United Kingdom",
      zip: "SW1A 1AA",
    },
    description: "A classic concert experience",
  },
  {
    date: new Date(2023, 11, 4),
    title: "The Beatles",
    venue: "The Royal Albert Hall",
    address: {
      street: "123 London Bridge",
      city: "London",
      state: "United Kingdom",
      zip: "SW1A 1AA",
    },
    description: "A classic concert experience",
  }
]
export const DUMMY_SONG_LIST = [
  "A Hard Day's Night",
  "Ticket To Ride",
  "Eight Days A Week",
  "Twist And Shout",
  "I Saw Her Standing There",
  "She Loves You",
  "All My Loving",
  "You Really Got A Hold On Me",
  "This Boy",
  "I Want To Hold Your Hand",
  "From Me To You",
  "Please Please Me",
  "Roll Over Beethoven",
  "Help!",
  "In My Life",
  "We Can Work It Out",
  "Day Tripper",
  "Long Tall Sally",
  "Sgt. Pepper's Lonely Hearts Club Band",
  "With A Little Help From My Friends",
  "Nowhere Man",
  "Yellow Submarine",
  "Tomorrow Never Knows	Back In The U.S.S.R.",
  "Octopus's Garden",
  "Birthday",
  "Helter Skelter",
  "Got To Get You Into My Life",
  "Drive My Car",
  "Something",
  "Come Together",
  "Get Back",
  "Taxman",
  "I'm Happy Just To Dance With You",
  "Any Time At All",
  "You Can't Do That",
  "Oh Darling",
  "Here Comes The Sun",
  "Because",
  "The End",
  "Honey Don't",
  "What You're Doing",
  "The Night Before",
  "You've Got To Hide Your Love Away",
  "I've Got A Feeling	One After 909",
  "Let It Be",
  "Magical Mystery Tour",
  "Strawberry Fields Forever",
  "Penny Lane",
  "Paperback Writer",
  "Rain",
  "Lady Madonna",
  "Revolution",
  "The Ballad Of John And Yoko",
  "Love Me Do",
  "She Said She Said",
  "Good Day Sunshine",
  "And Your Bird Can Sing",
  "I Want To Tell You",
  "What Goes On",
  "I'm Looking Through You",
  "If I Needed Someone",
  "Getting Better",
  "While My Guitar Gently Weeps",
  "Why Don't We Do It In The Road",
  "I Wanna Be Your Man"
]
export const DUMMY_IMAGE_URLS = [
  "band-pic1.avif",
  "band-pic2.avif",
  "band-pic3.avif",
  "band-pic4.avif",
  "band-pic5.avif",
  "band-pic6.avif",
  "band-pic7.avif",
  "band-pic8.avif",
  "band-pic9.avif",
  "band-pic10.avif"
];
